openapi: 3.0.3
info:
  title: RAG Chatbot API
  description: API for the Retrieval-Augmented Generation chatbot system
  version: 1.0.0
  contact:
    name: HackathonBook Team

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.hackathonbook.com
    description: Production server

paths:
  /rag/query:
    post:
      summary: Query the RAG system with full book context
      description: Submit a question to be answered using the entire book content for context
      operationId: queryFullBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response with answer and sources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      security:
        - bearerAuth: []

  /rag/selected_text_query:
    post:
      summary: Query the RAG system with selected text context only
      description: Submit a question to be answered using only the user-selected text
      operationId: querySelectedText
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectedTextQueryRequest'
      responses:
        '200':
          description: Successful response with answer (no sources for selection-only mode)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      security:
        - bearerAuth: []

  /rag/health:
    get:
      summary: Health check for the RAG service
      description: Check if the RAG service and its dependencies are available
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /rag/ingest:
    post:
      summary: Ingest book content into the RAG system
      description: Upload and process book content for RAG retrieval
      operationId: ingestBookContent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestionRequest'
      responses:
        '200':
          description: Content successfully ingested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The question or query to be answered
          example: "Explain the concept of forward kinematics in robotics"
        session_id:
          type: string
          description: Session identifier for maintaining conversation context
          example: "sess_abc123"
        book_id:
          type: string
          description: Identifier for the book to query
          example: "robotics_handbook_v1"

    SelectedTextQueryRequest:
      type: object
      required:
        - query
        - selected_text
      properties:
        query:
          type: string
          description: The question about the selected text
          example: "What does this paragraph mean?"
        selected_text:
          type: string
          description: The user-selected text to use as context
          example: "Forward kinematics is the process of determining the position and orientation of the end-effector..."
        session_id:
          type: string
          description: Session identifier for maintaining conversation context
          example: "sess_abc123"
        book_id:
          type: string
          description: Identifier for the book containing the selection
          example: "robotics_handbook_v1"

    QueryResponse:
      type: object
      required:
        - answer
        - session_id
      properties:
        answer:
          type: string
          description: The answer to the query
          example: "Forward kinematics is the process of determining the position and orientation..."
        session_id:
          type: string
          description: The session identifier
          example: "sess_abc123"
        sources:
          type: array
          description: List of sources used to generate the answer
          items:
            $ref: '#/components/schemas/SourceChunk'
        confidence:
          type: number
          description: Confidence score for the answer (0-1)
          example: 0.85

    SourceChunk:
      type: object
      properties:
        chunk_id:
          type: string
          description: Identifier for the source chunk
          example: "chunk_123"
        content:
          type: string
          description: The content of the source chunk
          example: "Forward kinematics is the process of determining the position and orientation of the end-effector..."
        page_number:
          type: integer
          description: Page number in the original book
          example: 45
        section_title:
          type: string
          description: Section title where the content appears
          example: "Chapter 3: Kinematics"

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Health status of the service
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: Time when the health check was performed
          example: "2025-12-17T10:30:00Z"
        services:
          type: object
          description: Status of dependent services
          properties:
            qdrant:
              type: string
              description: Status of Qdrant vector database
              example: "connected"
            neon:
              type: string
              description: Status of Neon database
              example: "connected"
            openai:
              type: string
              description: Status of OpenAI API
              example: "connected"

    IngestionRequest:
      type: object
      required:
        - book_id
        - content
        - title
      properties:
        book_id:
          type: string
          description: Unique identifier for the book
          example: "robotics_handbook_v1"
        title:
          type: string
          description: Title of the book
          example: "Robotics Handbook"
        content:
          type: string
          description: Full content of the book or chapter to be ingested
          example: "Chapter 1: Introduction to Robotics..."
        chunk_size:
          type: integer
          description: Size of text chunks for processing (default 1000)
          example: 1000
        overlap:
          type: integer
          description: Overlap between chunks (default 200)
          example: 200

    IngestionResponse:
      type: object
      required:
        - status
        - chunks_processed
      properties:
        status:
          type: string
          description: Status of the ingestion process
          example: "success"
        book_id:
          type: string
          description: Identifier of the book that was processed
          example: "robotics_handbook_v1"
        chunks_processed:
          type: integer
          description: Number of content chunks created
          example: 150
        processing_time:
          type: number
          description: Time taken to process in seconds
          example: 45.2

  responses:
    BadRequest:
      description: Bad request - invalid input parameters
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: "Invalid query parameters"
              message:
                type: string
                description: Detailed error description
                example: "Query parameter is required and must be a non-empty string"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: "Internal server error"
              message:
                type: string
                description: Detailed error description
                example: "An unexpected error occurred while processing the request"