openapi: 3.0.0
info:
  title: Authentication API
  description: API for user authentication and background information management
  version: 1.0.0
paths:
  /api/auth/signup:
    post:
      summary: User signup with background questionnaire
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                name:
                  type: string
                softwareExperience:
                  type: string
                  enum: [beginner, intermediate, advanced, expert]
                hardwareExperience:
                  type: string
                  enum: [beginner, intermediate, advanced, expert]
                primaryFocus:
                  type: string
                  enum: [software, hardware, both, theory]
                backgroundDetails:
                  type: string
              required:
                - email
                - password
                - softwareExperience
                - hardwareExperience
                - primaryFocus
      responses:
        '200':
          description: User successfully created with authentication session
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
                  userBackground:
                    $ref: '#/components/schemas/UserBackground'
        '400':
          description: Invalid input data
        '409':
          description: User with this email already exists

  /api/auth/signin:
    post:
      summary: User sign in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: User successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '400':
          description: Invalid credentials
        '401':
          description: Authentication failed

  /api/auth/me:
    get:
      summary: Get current user information
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  userBackground:
                    $ref: '#/components/schemas/UserBackground'
        '401':
          description: Not authenticated

  /api/user-background:
    put:
      summary: Update user background information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBackgroundUpdate'
      responses:
        '200':
          description: User background updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBackground'
        '401':
          description: Not authenticated

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        emailVerified:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - email
        - createdAt
        - updatedAt

    Session:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - userId
        - expiresAt
        - createdAt
        - updatedAt

    UserBackground:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        softwareExperience:
          type: string
          enum: [beginner, intermediate, advanced, expert]
        hardwareExperience:
          type: string
          enum: [beginner, intermediate, advanced, expert]
        primaryFocus:
          type: string
          enum: [software, hardware, both, theory]
        backgroundDetails:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - userId
        - softwareExperience
        - hardwareExperience
        - primaryFocus
        - createdAt
        - updatedAt

    UserBackgroundUpdate:
      type: object
      properties:
        softwareExperience:
          type: string
          enum: [beginner, intermediate, advanced, expert]
        hardwareExperience:
          type: string
          enum: [beginner, intermediate, advanced, expert]
        primaryFocus:
          type: string
          enum: [software, hardware, both, theory]
        backgroundDetails:
          type: string