import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from filesystem structure to include all book content
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Introduction',
      items: [{type: 'autogenerated', dirName: 'intro'}],
    },
    {
      type: 'category',
      label: 'Module 1: Robotic Nervous System',
      items: [{type: 'autogenerated', dirName: 'module-1-robotic-nervous-system'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [{type: 'autogenerated', dirName: 'module-2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain',
      items: [{type: 'autogenerated', dirName: 'module-3-ai-robot-brain'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      items: [{type: 'autogenerated', dirName: 'module-4-vision-language-action'}],
    },
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
    'context7-integration',
    'github-integration'
  ],
};

export default sidebars;
